<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Email Subject</title>
    <style>
        /* Reset styles to ensure consistent rendering */
        body {
            margin: 0;
            padding: 0;
        }

        /* Add styles to your email content */
        .email-content {
            background-color: #f2f2f2;
            font-family: Arial, sans-serif;
            font-size: 16px;
            line-height: 1.5;
            padding: 20px;
            max-width: 600px;
            margin: 2rem auto 0;
        }

        h1 {
            font-size: 28px;
            font-weight: bold;
            margin-top: 0;
        }

        p {
            margin-bottom: 20px;
        }

        a {
            color: #0088cc;
            text-decoration: none;
        }
    </style>
</head>

<body>
    <div class="email-content">
        <h1>Contact Request From Customers</h1>
        <p>Hello Admin,</p>
        <p>
            We hope this message finds you well.
            We wanted to inform you that a new contact form submission has been received on our website.
            We thought you'd like to know that there is a new inquiry waiting for your attention.
        </p>
        <p> Please log in to our website's admin panel to view the details of the submission and respond accordingly.
            We encourage you to respond to the inquiry as soon as possible,
            as timely responses are an essential part of providing excellent customer service.
            The details of the Contact request are as follows:
        </p>
        <p>
        <h4> Name : <span>%username%</span> </h4>
        <h4> Email : <span>%usermail%</span> </h4>
        <h4> Phone Number : <span>%userphno%</span> </h4>
        <h4> Notes : <span>%message%</span> </h4>
        </p>
        <p>Thank you for your attention to this matter, and we appreciate your efforts in providing excellent customer service.
        </p>
        <p>Best regards,</p>
        <p>Starling bags</p>
    </div>
</body>

</html>