<div class="loaderMainContainer"><div class="loaderChildContainer">
<div></div>
</div></div>
<style type="text/css">
@keyframes loaderChildContainer {
  0% { transform: rotate(0deg) }
  50% { transform: rotate(180deg) }
  100% { transform: rotate(360deg) }
}
.loaderChildContainer div {
  position: absolute;
  animation: loaderChildContainer 1s linear infinite;
  width: 80px;
  height: 80px;
  top: 10px;
  left: 10px;
  border-radius: 50%;
  box-shadow: 0 2px 0 0 #ffffff;
  transform-origin: 40px 41px;
}
.loaderMainContainer {
  width: 24px;
  height: 24px;
  display: none;
  overflow: hidden;
  /* background: #ffffff; */
}
.loaderChildContainer {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.24);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.loaderChildContainer div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>