<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Email Subject</title>
    <style>
        /* Reset styles to ensure consistent rendering */
        body {
            margin: 0;
            padding: 0;
        }

        /* Add styles to your email content */
        .email-content {
            background-color: #f2f2f2;
            font-family: Poppins;
            font-size: 16px;
            line-height: 1.5;
            padding: 20px;
            max-width: 600px;
            margin: 2rem auto 0;
        }

        h1 {
            font-size: 28px;

            margin-top: 0;
        }

        p {
            margin-bottom: 20px;
        }

        a {
            /* margin: 155px;
            color: #0088cc;
            text-decoration: none;
            border-radius: 8px solid;
            background-color: #0088cc;
            color: #f2f2f2;
            padding: 12px 24px; */

            box-sizing: border-box;
            border-color: #348eda;
            font-weight: 400;
            text-decoration: none;
            display: inline-block;
            margin: 15px 0px 15px 155px;
            color: #ffffff;
            background-color: #348eda;
            border: solid 1px #348eda;
            border-radius: 2px;
            font-size: 16px;
            padding: 12px 45px;
        }
    </style>
</head>

<body>
    <div class="email-content">
        <h1>Password Reset Link from Starling bags</h1>
        <p>Hello Admin,</p>
        <p>
            we got a request for you to reset Password!
            Click the link bellow: </p>
        <a href='https://starlingbagsni.co.uk/updatePassword.php?email=%mail% &reset_token=%token%'>Reset Password</a>
    </div>
</body>

</html>