<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Email Subject</title>
    <style>
        /* Reset styles to ensure consistent rendering */
        body {
            margin: 0;
            padding: 0;
        }

        /* Add styles to your email content */
        .email-content {
            background-color: #f2f2f2;
            font-family: Poppins;
            font-size: 16px;
            line-height: 1.5;
            padding: 20px;
            max-width: 600px;
            margin: 2rem auto 0;
        }

        h1 {
            font-size: 28px;
            font-weight: bold;
            margin-top: 0;
        }

        p {
            margin-bottom: 20px;
        }

        a {
            color: #0088cc;
            text-decoration: none;
        }
    </style>
</head>

<body>
    <div class="email-content">
        <h1>Welcome To Starling bags !!!</h1>
        <p>Hello %username% ,</p>
        <p>
            Thank you for reaching out to us via our contact form. We appreciate your interest in our services and will do our best to respond to your inquiry as soon as possible.
        </p>
        <p>Thank you for considering our services, and we look forward to speaking with you soon.</p>
        <p>Best regards,</p>
        <p>Starling bags</p>
    </div>
</body>

</html>